<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>plansys2_examples</name>
  <version>3.0.0</version>

  <description>ROS2 Planning System Examples</description>

  <maintainer email="fmrico@gmail.com">Francisco Martin Rico</maintainer>

  <license>Apache License, Version 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>plansys2_bt_example</exec_depend>
  <exec_depend>plansys2_cascade_example</exec_depend>
  <exec_depend>plansys2_multidomain_example</exec_depend>
  <exec_depend>plansys2_patrol_navigation_example</exec_depend>
  <exec_depend>plansys2_simple_example</exec_depend>
  <exec_depend>plansys2_simple_example_py</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
